# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41f95b88ac6952b6701b2336a8256148f2bcae8420681ce5277efdae747503460172c3b8e9f8a1f669b67e0d81ba6655bcd3a907549d5eadc3cff92706a26d7e

test:
  secret_key_base: c1c42b7853249b716daa37e599c8cc17022f3bcadd155b02bd79b3049425eeedc93bf8424c07c458d6719fa784d40e75aff92d1be9bfcdd1e086c9429ccc02fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
